# Generated by OpenQL 0.10.0 for program my_program
version 1.2

pragma @ql.name("my_program")


.my_kernel
    ym90 q[0]
    x45 q[1]
    x45 q[2]
    x q[3]
    y45 q[4]
    cz q[0], q[4]
    y90 q[2]
    x45 q[0]
    cz q[0], q[1]
    cz q[4], q[1]
    xm90 q[0]
    cz q[3], q[0]
    xm90 q[1]
    x90 q[4]
    cz q[3], q[2]
