# Generated by OpenQL 0.10.0 for program my_program
version 1.2

pragma @ql.name("my_program")


.my_kernel
    { # start at cycle 0
        ym90 q[0]
        y45 q[4]
    }
    cz q[0], q[4]
    skip 2
    { # start at cycle 4
        x45 q[1]
        x45 q[0]
    }
    cz q[0], q[1]
    skip 1
    x45 q[2]
    { # start at cycle 8
        x q[3]
        y90 q[2]
        cz q[4], q[1]
        xm90 q[0]
    }
    { # start at cycle 9
        cz q[3], q[0]
        cz q[3], q[2]
    }
    skip 1
    { # start at cycle 11
        xm90 q[1]
        x90 q[4]
    }
